services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      test: ["CMD", "/healthchecks/redis.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - ./healthchecks:/healthchecks
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/healthchecks/postgres.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - back-tier

  vote-1:
    build: vote/.
    container_name: vote-1
    networks:
      - front-tier
      - back-tier
    depends_on:
      redis:
        condition: service_healthy

  vote-2:
    build: vote/.
    container_name: vote-2
    networks:
      - front-tier
      - back-tier
    depends_on:
      redis:
        condition: service_healthy
  
  nginx:
    build: nginx/.
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./healthchecks:/healthchecks
    # healthcheck:
    #   test: ["CMD", "/healthchecks/vote.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    networks:
      - front-tier
    depends_on:
      vote-1:
        condition: service_started
      vote-2:
        condition: service_started

  result:
    build: result/.
    image: result
    container_name: result
    ports:
      - "4000:4000"
    networks:
      - front-tier
      - back-tier
    depends_on:
      db:
        condition: service_healthy

  seed:
    build: seed-data/.
    image: seed-data
    container_name: seed
    networks:
      - front-tier
    depends_on:
      nginx:
        condition: service_started

  worker:
    build: worker/.
    image: worker
    container_name: worker
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge

volumes:
  db-data:
