apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/cloud-login-489913/zones/europe-west3-c/disks/gce-disk
    fsType: ext4