apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard-rwo"
  volumeName: db-data-pv
  resources:
    requests:
      storage: 1Gi