apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: seed
        image: europe-west3-docker.pkg.dev/cloud-login-489913/cloud-login/seed-data:latest
      restartPolicy: Never
  backoffLimit: 4
